config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-reporting-plugins:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-reporting-plugins
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-burgundy-sheep.sh
        container: qc.acc_dorky-red-dane
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cornflower-vole.sh
        container: qc.doc_tacky-orange-nightingale
      github.com/eosc-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-black-rottweiler.sh
        container: qc.doc_pokey-tomato-bee
      github.com/eosc-synergy/sqaaas-reporting-plugins markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-maroon-hamster.sh
        container: qc.doc_sloppy-russet-bison
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-grey-coati.sh
        container: qc.lic_cranky-chocolate-hippopotamus
  QC.Met:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-heliotrope-vulture.sh
        container: qc.met_crappy-sapphire-fousek
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-gamboge-walrus.sh
        container: qc.sec_snazzy-olive-swan
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-black-bandicoot.sh
        container: qc.sty_skanky-ivory-seal
      github.com/eosc-synergy/sqaaas-reporting-plugins jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olivine-bombay.sh
        container: qc.sty_woolly-dandelion-lion
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-reporting-plugins get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-salmon-okapi.sh
        container: qc.ver_seedy-asparagus-turkey
timeout: 5400
